#!/usr/bin/env python3
"""
Bourbier Printer — print pipeline for Epson TM-T88V.

Backends
────────
  WindowsGdiBackend   Windows only
    Draws the image into a Windows Printer Device Context via win32ui + PIL.ImageWin.
    This is the exact same path as the Epson TM-T88V Utility software:
    GDI → Epson driver rasteriser → printer-native commands → USB.
    No ESC/POS generated by us. No buffer management. No white bands.

  UsbBackend          macOS / Linux
    Generates ESC/POS via python-escpos Dummy, then sends via raw pyusb.
    Fresh device handle per job + dispose_resources() to avoid stale IOKit state.
    7.2 KB chunks + 30 ms sleep to stay above the 32 KB printer buffer limit.

Setup
─────
  pip install python-escpos Pillow
  Windows : also pip install pywin32
            install the official Epson TM-T88V driver
            set PRINTER_NAME in .env (default: "EPSON TM-T88V")
  macOS   : brew install libusb

Usage
─────
  python3 print_escpos.py <image.png>
"""

from __future__ import annotations

import os
import sys
import time
from abc import ABC, abstractmethod
from PIL import Image


# ═══════════════════════════════════════════════════════════════════
# Logging
# ═══════════════════════════════════════════════════════════════════

def _log(msg: str) -> None:
    print(msg, file=sys.stderr)


# ═══════════════════════════════════════════════════════════════════
# Backends
# ═══════════════════════════════════════════════════════════════════

class PrinterBackend(ABC):
    @abstractmethod
    def print_image(self, img: Image.Image) -> None: ...


class WindowsGdiBackend(PrinterBackend):
    """
    Prints via Windows GDI — identical path to Epson TM-T88V Utility software.

    Why GDI instead of win32print RAW:
      Sending raw ESC/POS GS v 0 via win32print still causes white bands because
      the Epson driver passes the command as-is to the printer, which then has to
      manage its own internal buffer — and fails with large images.
      With GDI, the Epson driver's own rasteriser breaks the image into whatever
      printer-native commands the TM-T88V needs, with correct buffering.
      Result: same quality as the official Epson Utility, zero white bands.
    """

    def __init__(self, printer_name: str) -> None:
        self.printer_name = printer_name

    def print_image(self, img: Image.Image) -> None:
        import win32ui
        from PIL import ImageWin

        _log(f"  printer : {self.printer_name}")

        hDC = win32ui.CreateDC()
        hDC.CreatePrinterDC(self.printer_name)

        # Printable width in device pixels as reported by the Epson driver
        printer_w = hDC.GetDeviceCaps(8)   # HORZRES
        printer_h = hDC.GetDeviceCaps(10)  # VERTRES
        _log(f"  dc      : {printer_w} × {printer_h} px (driver DPI)")

        # Scale image to fit printable width, preserve aspect ratio
        scaled_h = round(img.height * printer_w / img.width)
        _log(f"  image   : {img.width} × {img.height} → {printer_w} × {scaled_h} px")

        hDC.StartDoc("Bourbier Photo")
        hDC.StartPage()

        dib = ImageWin.Dib(img.convert("RGB"))
        dib.draw(hDC.GetHandleOutput(), (0, 0, printer_w, scaled_h))

        hDC.EndPage()
        hDC.EndDoc()
        hDC.DeleteDC()
        _log("  status  : GDI job sent to spooler")


class UsbBackend(PrinterBackend):
    """
    macOS / Linux: raw ESC/POS via pyusb, fresh handle per job.

    Why fresh handle per job:
      On macOS/IOKit, a failed job leaves pending transfers in the libusb pipe.
      Reusing the handle means the next job inherits that broken state (~500 ms
      first write, then immediate STALL). dispose_resources() releases the IOKit
      reference without touching the device — never call clear_halt() on macOS.
    """

    VID   = 0x04b8
    PID   = 0x0e02
    CHUNK = 7200    # 100 rows × 72 B = 7.2 KB < 32 KB printer receive buffer
    SLEEP = 0.030   # s between chunks: printer needs ~50 ms for 7.2 KB;
                    # next chunk arrives at ~37 ms — 13 ms margin, no white bands

    def print_image(self, img: Image.Image) -> None:
        data = self._to_escpos(img)
        self._send(data)

    def _to_escpos(self, img: Image.Image) -> bytes:
        from escpos.printer import Dummy

        d = Dummy(profile="TM-T88V")
        # python-escpos profile says 512 px; correct value for 80 mm = 576 dots
        d.profile.profile_data["media"]["width"]["pixels"] = 576
        d._raw(b"\x1b\x40")  # ESC @ — reset printer settings
        d.image(img)
        d.cut()
        data: bytes = d.output
        n = (len(data) + self.CHUNK - 1) // self.CHUNK
        _log(f"  ESC/POS : {len(data):,} B  →  {n} chunks of {self.CHUNK} B + {self.SLEEP*1000:.0f} ms sleep")
        return data

    def _send(self, data: bytes) -> None:
        import usb.core
        import usb.util

        dev = usb.core.find(idVendor=self.VID, idProduct=self.PID)
        if dev is None:
            raise RuntimeError(f"Printer {self.VID:04x}:{self.PID:04x} not found")

        try:
            usb.util.claim_interface(dev, 0)
            cfg  = dev.get_active_configuration()
            intf = cfg[(0, 0)]
            ep   = usb.util.find_descriptor(
                intf,
                custom_match=lambda e:
                    usb.util.endpoint_direction(e.bEndpointAddress)
                    == usb.util.ENDPOINT_OUT,
            )
            if ep is None:
                raise RuntimeError("No bulk OUT endpoint found")

            total    = len(data)
            n_chunks = (total + self.CHUNK - 1) // self.CHUNK
            _log("  " + "─" * 46)

            for i in range(0, total, self.CHUNK):
                chunk = data[i : i + self.CHUNK]
                idx   = i // self.CHUNK + 1
                t0    = time.perf_counter()
                ep.write(chunk, timeout=3000)
                ms    = (time.perf_counter() - t0) * 1000
                _log(f"  [{idx:02d}/{n_chunks}]  {i:6d}–{i+len(chunk):6d} B  {ms:6.1f} ms")
                if i + self.CHUNK < total:
                    time.sleep(self.SLEEP)

            _log("  " + "─" * 46)

        finally:
            try:
                usb.util.release_interface(dev, 0)
            except Exception:
                pass
            usb.util.dispose_resources(dev)
            _log("  USB     : handle released + disposed")


def get_backend() -> PrinterBackend:
    if os.name == "nt":
        name = os.environ.get("PRINTER_NAME", "EPSON TM-T88V")
        return WindowsGdiBackend(name)
    return UsbBackend()


# ═══════════════════════════════════════════════════════════════════
# Image adjustments
# ═══════════════════════════════════════════════════════════════════

def _adjust(img: Image.Image) -> Image.Image:
    """
    Apply quality controls from environment variables.

    PRINT_BRIGHTNESS  float  default 1.0  — 0.5 = darker  2.0 = lighter
    PRINT_CONTRAST    float  default 1.0  — 0.5 = flat     2.0 = punchy
    PRINT_SHARPNESS   float  default 1.0  — 0.0 = blurred  2.0 = sharp edges
    PRINT_MULTITONE   0|1    default 1    — 1 = keep 8-bit gray (driver dithers)
                                            0 = pre-convert to 1-bit (Floyd-Steinberg)

    All values are applied before the image is handed to the backend.
    Tune them in bourbier-printer/.env without touching any code.
    """
    from PIL import ImageEnhance

    brightness = float(os.environ.get("PRINT_BRIGHTNESS", "1.0"))
    contrast   = float(os.environ.get("PRINT_CONTRAST",   "1.0"))
    sharpness  = float(os.environ.get("PRINT_SHARPNESS",  "1.0"))
    multitone  = os.environ.get("PRINT_MULTITONE", "1") != "0"

    _log(f"  brightness={brightness}  contrast={contrast}  sharpness={sharpness}  multitone={'on' if multitone else 'off'}")

    if brightness != 1.0:
        img = ImageEnhance.Brightness(img).enhance(brightness)
    if contrast != 1.0:
        img = ImageEnhance.Contrast(img).enhance(contrast)
    if sharpness != 1.0:
        img = ImageEnhance.Sharpness(img).enhance(sharpness)

    if not multitone:
        # Pre-dither to 1-bit (Floyd-Steinberg via Pillow), then back to L
        img = img.convert("1").convert("L")

    return img


# ═══════════════════════════════════════════════════════════════════
# Entry point
# ═══════════════════════════════════════════════════════════════════

def main() -> None:
    if len(sys.argv) < 2:
        _log("Usage: print_escpos.py <image.png>")
        sys.exit(1)

    img_path = sys.argv[1]
    backend  = get_backend()

    _log(f"\n{'═' * 50}")
    _log(f"source  : {img_path}")
    _log(f"backend : {backend.__class__.__name__}")

    img = Image.open(img_path).convert("L")
    _log(f"  image   : {img.width} × {img.height} px")
    img = _adjust(img)

    # 1-bit debug: white bands here → dithering issue; absent → USB/transport issue
    debug = img_path.replace(".png", "_1bit.png")
    img.convert("1").save(debug)
    _log(f"  1-bit   : {debug}")

    t0 = time.perf_counter()
    backend.print_image(img)
    _log(f"total   : {time.perf_counter() - t0:.2f} s")
    _log(f"{'═' * 50}\n")


if __name__ == "__main__":
    main()
